# Nombre del Workflow
name: Deploy to WordPress.org Plugin Repository

# Disparador (Trigger)
# Esto se ejecutará CADA VEZ que publiques una "Release" en GitHub
on:
  release:
    types: [published]

# Tareas (Jobs)
jobs:
  deploy:
    runs-on: ubuntu-latest # Usar la última imagen de Ubuntu
    steps:
      # 1. Checkout del código de tu repositorio GitHub
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Asegura que tengamos todo el historial para la acción

      # 2. La acción principal: Despliegue en WordPress.org
      # Esta es una acción mantenida por la comunidad (10up) muy fiable
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-svn-deploy@stable
        with:
          # El "slug" de tu plugin en el repositorio de WP.org
          plugin_slug: "pedido-minimo-for-woocommerce"
          
          # Nombre del fichero readme.txt (generalmente es este)
          plugin_readme: "readme.txt"

        # Mapeo de los "Secrets" a variables de entorno que la acción espera
        env:
          WP_ORG_USERNAME: ${{ secrets.WP_ORG_USERNAME }}
          WP_ORG_PASSWORD: ${{ secrets.WP_ORG_PASSWORD }}
          # SVN_USERNAME y SVN_PASSWORD son alias que la acción también acepta
          SVN_USERNAME: ${{ secrets.WP_ORG_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WP_ORG_PASSWORD }}
